site_name: Moxies nix Docs
nav:
  - Home: index.md
  - Dotfiles:
    - Common: common.md
    - Home Manager: home.md
    - Modules: modules.md
    - Packages: packages.md
    - Devshells: templates.md
  - Nix Book: nix.md
  - License: LICENSE

