# @generated by https://codeberg.org/goldstein/unflake
let
  indirect_deps = {
  };
  specs = rec {
  };
  deps = indirect_deps // builtins.mapAttrs (_: spec: builtins.fetchTree spec) specs;
  injections = rec {
  };
  inject = name: flake_path: subdir:
    let
      inputs = builtins.mapAttrs (_: dep: universe.${dep}) injections.${name} // {
        inherit self;
      };
      sourceInfo = deps.${name};
      outPath = "${sourceInfo.outPath}${subdir}";
      outputs = (import "${sourceInfo.outPath}/${flake_path}").outputs inputs;
      self = outputs // sourceInfo // {
        inherit inputs outputs outPath sourceInfo;
        _type = "flake";
        _flake = true;
      };
    in self;
  universe = rec {
  };
  inputs = {
  };
in inputs // {
  withInputs = fn: let outputs = fn (inputs // { inherit self; }); self = outputs // {
    inherit inputs outputs;
    _type = "flake";
    outPath = builtins.toString ./.;
  }; in self;
  __functor = self: self.withInputs;
  self = throw "to use inputs.self, write `import ./unflake.nix (inputs: ...)`";
  _unflake = { inherit specs deps injections; };
}
